baseURL: "https://yuminghuo.github.io"
languageCode: en-us
title: Becky Lei
theme: PaperMod
defaultContentLanguage: en
defaultContentLanguageInSubdir: true

languages:
  en:
    languageName: "English"
    languageCode: "en"
    contentDir: "content/English"
    menu:
      main:
        - identifier: search
          name: Search
          url: /search/
          weight: 50
    params:
      defaultTheme: dark
      ShowShareButtons: false
      ShowReadingTime: true
      author: ["Yuming"]
      ShowBreadCrumbs: true
      ShowPostNavLinks: true
      profileMode:
        enabled: true
        title: "Becky Lei"
        subtitle: "University of Bristol"
        imageUrl: "img/pp.JPG"
        imageTitle: "Becky"
        imageWidth: 160
        imageHeight: 230
        buttons:
          - name: About me
            url: "/en/about/"
          # - name: My project
          #   url: "/en/project/"
          - name: My intership
            url: "/en/inter/"
          - name: Resume
            url: "/pdf/becky.pdf"
      socialIcons:
        - name: "Github"
          url: "https://github.com/beckyyylei"
        - name: "email"
          url: "mailto:beckylei1215@outlook.com"
        # - name: "Discord"
        #   url: "https://discordapp.com/users/huoh"
    
  zh:
    languageName: "ä¸­æ–‡"
    languageCode: "zh"
    contentDir: "content/Chinese"
    title: "é›·å®‡æ˜Ÿ"
    menu:
      main:
        - identifier: search
          name: æœç´¢ğŸ”
          url: /search/
          weight: 50
    params:
      defaultTheme: dark
      ShowShareButtons: false
      ShowReadingTime: true
      author: ["Yuming"]
      ShowBreadCrumbs: true
      ShowPostNavLinks: true
      profileMode:
        enabled: true
        title: "é›·å®‡æ˜Ÿ"
        subtitle: "å¸ƒé‡Œæ–¯æ‰˜å¤§å­¦ç¡•å£«"
        imageUrl: "img/pp.JPG"
        imageTitle: "becky"
        imageWidth: 160
        imageHeight: 230
        buttons:
          - name: å…³äºæˆ‘
            url: "/zh/about/"
          # - name: é¡¹ç›®ç»å†
          #   url: "/zh/project/"
          - name: å®ä¹ ç»å†
            url: "/zh/inter/"
          - name: ç®€å†
            url: "/pdf/cv.pdf"
      socialIcons:
        - name: "Github"
          url: "https://github.com/beckyyylei"
        - name: "email"
          url: "mailto:bekcylei1215@outlook.com"
        - name: "Discord"
          url: "https://discordapp.com/users"
