baseURL: "https://yuminghuo.github.io"
languageCode: en-us
title: Becky Lei
theme: PaperMod
defaultContentLanguage: en
defaultContentLanguageInSubdir: true

# å…è®¸åœ¨ Markdown ä¸­ä½¿ç”¨ HTML æ ‡ç­¾
markup:
  goldmark:
    renderer:
      unsafe: true

languages:
  en:
    languageName: "English"
    languageCode: "en"
    contentDir: "content/English"
    menu:
      main:
        - identifier: search
          name: Search
          url: /search/
          weight: 50
    params:
      defaultTheme: dark
      ShowShareButtons: false
      ShowReadingTime: true
      author: ["Becky"]
      ShowBreadCrumbs: true
      ShowPostNavLinks: true
      profileMode:
        enabled: true
        title: "Yuxing(Becky) Lei"
        subtitle: "Master of Psychology of Education (University of Bristol), 2023 - 2024 <br> 
        Bachelor of Applied Psychology (Hong Kong Metropolitan University), 2019 - 2023 <br>
        Bachelor of Business Management (Hong Kong Metropolitan University), 2019 - 2023"
        imageUrl: "img/pp.JPG"
        imageTitle: "Becky"
        imageWidth: 160
        imageHeight: 230
        buttons:
          - name: About me
            url: "/en/about/"
          - name: Certificates
            url: "/en/certificates/"
          - name: My intership
            url: "/en/inter/"
          - name: Resume
            url: "/pdf/cv.pdf"
      socialIcons:
        - name: "email"
          url: "mailto:beckylei1215@outlook.com"
    
  zh:
    languageName: "ä¸­æ–‡"
    languageCode: "zh"
    contentDir: "content/Chinese"
    title: "é›·å®‡æ˜Ÿ"
    menu:
      main:
        - identifier: search
          name: æœç´¢ğŸ”
          url: /search/
          weight: 50
    params:
      defaultTheme: dark
      ShowShareButtons: false
      ShowReadingTime: true
      author: ["Becky"]
      ShowBreadCrumbs: true
      ShowPostNavLinks: true
      profileMode:
        enabled: true
        title: "é›·å®‡æ˜Ÿ"
        subtitle: "æ•™è‚²å¿ƒç†å­¦ç¡•å£« (å¸ƒé‡Œæ–¯æ‰˜å¤§å­¦), 2023 - 2024 å¹´ <br>
        åº”ç”¨å¿ƒç†å­¦å­¦å£« (é¦™æ¸¯éƒ½ä¼šå¤§å­¦), 2019 - 2023 å¹´ <br>
        å·¥å•†ç®¡ç†å­¦å£« (é¦™æ¸¯éƒ½ä¼šå¤§å­¦), 2019 - 2023 å¹´"
        imageUrl: "img/pp.JPG"
        imageTitle: "becky"
        imageWidth: 160
        imageHeight: 230
        buttons:
          - name: å…³äºæˆ‘
            url: "/zh/about/"
          - name: è·å¥–ç»å†
            url: "/zh/certificates/"
          - name: å®ä¹ ç»å†
            url: "/zh/inter/"
          - name: ç®€å†
            url: "/pdf/chinese.pdf"
      socialIcons:
        - name: "email"
          url: "mailto:bekcylei1215@outlook.com"